# Supabase / PostgreSQL connection
spring.datasource.url=jdbc:postgresql://db.pmifolvsrtvxlqduyefc.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Zi8v!Hqj9Ld$$eK
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Port configuration for Render/Heroku
server.port=${PORT:8080}
